### ISSUE TITLE
Aborting stand-alone image build due to reflection use without configuration.

### ISSUE THREAD

**Issue by devurandom** [clj-easy/graal-docs#55]
Stand alone images do not build here, because:
```
Warning: Reflection method java.lang.Class.forName invoked at clojure.lang.RT.classForName(RT.java:2212)
Warning: Reflection method java.lang.Class.getMethod invoked at clojure.lang.Reflector.tryFindMethod(Reflector.java:75)
Warning: Reflection method java.lang.Class.getMethod invoked at clojure.lang.Reflector.getMethods(Reflector.java:511)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.lang.Reflector.getMethods(Reflector.java:498)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.lang.Reflector.getAsMethodOfPublicBase(Reflector.java:180)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.lang.Reflector.getMethods(Reflector.java:535)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.core$filter_methods$fn__7521.invoke(genclass.clj:29)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.lang.Compiler$StaticFieldExpr.<init>(Compiler.java:1288)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.lang.Reflector.getAsMethodOfAccessibleBase(Reflector.java:240)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.core$generate_class$fn__7642.invoke(genclass.clj:423)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.lang.Compiler$StaticInvokeExpr.parse(Compiler.java:3567)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.lang.Reflector.getAsMethodOfPublicBase(Reflector.java:191)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.core$generate_proxy$fn__7085$fn__7089.invoke(core_proxy.clj:213)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.lang.Reflector.getAsMethodOfAccessibleBase(Reflector.java:229)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.core$generate_proxy$iter__7097__7103$fn__7104.invoke(core_proxy.clj:230)
Warning: Reflection method java.lang.Class.getMethods invoked at clojure.lang.Compiler$NewInstanceExpr.gatherMethods(Compiler.java:8352)
Warning: Reflection method java.lang.Class.getDeclaredMethods invoked at clojure.core$filter_methods$fn__7521.invoke(genclass.clj:28)
Warning: Reflection method java.lang.Class.getDeclaredMethods invoked at clojure.core$generate_proxy$fn__7085$fn__7089.invoke(core_proxy.clj:212)
Warning: Reflection method java.lang.Class.getDeclaredMethods invoked at clojure.lang.Compiler$NewInstanceExpr.gatherMethods(Compiler.java:8350)
Warning: Reflection method java.lang.Class.getConstructors invoked at clojure.lang.Compiler$NewExpr.<init>(Compiler.java:2579)
Warning: Reflection method java.lang.Class.getConstructors invoked at clojure.lang.LispReader$CtorReader.readRecord(LispReader.java:1473)
Warning: Reflection method java.lang.Class.getConstructors invoked at clojure.lang.Compiler$ObjExpr.emitValue(Compiler.java:4803)
Warning: Reflection method java.lang.Class.getConstructors invoked at clojure.lang.Reflector.invokeConstructor(Reflector.java:278)
Warning: Reflection method java.lang.Class.getDeclaredConstructors invoked at clojure.core$generate_proxy.invokeStatic(core_proxy.clj:141)
Warning: Reflection method java.lang.Class.getDeclaredConstructors invoked at clojure.core$ctor_sigs.invokeStatic(genclass.clj:60)
Warning: Reflection method java.lang.Class.getField invoked at clojure.lang.Compiler$StaticFieldExpr.<init>(Compiler.java:1284)
Warning: Reflection method java.lang.Class.getFields invoked at clojure.lang.Reflector.getField(Reflector.java:487)
Warning: Reflection method java.lang.Class.getDeclaredFields invoked at clojure.core$find_field.invokeStatic(genclass.clj:79)
Warning: Aborting stand-alone image build due to reflection use without configuration.
```

1. What are the implications of passing `--no-fallback`? Is it safe?
2. How do I fix this?

**Comment by borkdude** [comment]
See https://github.com/clj-easy/graal-docs#reflection. I don't recommend building with `--no-fallback` since that results in just a thing which invokes the JVM.

**Comment by devurandom** [comment]
> See https://github.com/clj-easy/graal-docs#reflection.

Sorry, I did not fully understand that section.

I need `-H:ReflectionConfigurationFiles=reflect-config.json`. Do I understand the section correctly that I cannot create `reflect-config.json` just from the warnings quoted above, because neither `java.lang.Class` nor e.g. `clojure.lang.Reflector` are the classes I need to list in `reflect-config.json`? Instead I need to find out why e.g. `clojure.lang.Reflector` uses `java.lang.Class` when Clojure compiles certain code? E.g. there might be a `java.lang.String` that is being passed to some overloaded method and I need to list `java.lang.String` in `reflect-config.json`? (And the class of the method that causes reflection is not the one that needs to be listed there, either?)

Instead I need to run my JAR with a regular JRE with `-agentlib:native-image-agent...`? (The link to the documentation for that seems outdated and should be https://www.graalvm.org/22.0/reference-manual/native-image/Agent/#assisted-configuration-of-native-image-builds.)

Is the `filter.json` quoted in that section a recommendation or just an example? (The documentation for that appears to be gone, at least from the page linked to.)
```json
{"rules": [
  {"excludeClasses": "clojure.**"},
  {"includeClasses": "clojure.lang.Reflector"}]}
```

What exactly is a "false positive" in this context? Something where Graal thinks reflection is being used, but it is not actually being used? Could you please give an example for that?

Since the reflection configuration can change at any time, I need to run my application with `-agentlib:native-image-agent...` every time I build it?
